package custom.code;

public enum MessageCode {

    NO_DRIVING_LICENSE,
    SUCCESS_CREATE_MANDATE,
    USER_NOT_FOUND,
    USER_NOT_ACTIVE,
    SUCCESS_CREATE_PUBLIC_USER,
    SUCCESS_CREATE_PRIVATE_USER,
    SUCCESS_CREATE_ADMINISTRATOR_USER,
    SUCCESS_ADD_ADMINISTRATOR_ROLE,
    SUCCESS_ADD_PRIVATE_ROLE,
    SUCCESS_REMOVE_ADMINISTRATOR_ROLE,
    SUCCESS_REMOVE_PRIVATE_ROLE,
    SUCCESS_EDIT_USER_ACCOUNT,
    SUCCESS_ACTIVE_USER,
    SUCCESS_INACTIVE_USER

}
